language: ruby
before_install:
  - "sudo apt-get install -qq libssl-dev"
before_script:
  - "./install.sh"
script: "rake travis"
env:
  - CI_TESTS=rubyspec
  - CI_TESTS=vmunit
  - CI_TESTS=vmunit2
  - CI_TESTS=p_tests
  # These next ones have to be cleaned up, they don't currently pass
  # - CI_TESTS=fav_gems
  # - CI_TESTS=sinatra
  # - CI_TESTS=examples
notifications:
    email: false
    irc: "irc.freenode.org#maglev-ruby"
    webhooks:
      urls:
        - https://webhooks.gitter.im/e/40b9abc1ab238ef1ebb2
        on_success: change
        on_failure: always
        on_start: false

