language: ruby
before_script:
  - "./install.sh"
script: "rake travis"
env:
  - CI_TESTS=rubyspec
  - CI_TESTS=vmunit
  - CI_TESTS=vmunit2
  # These next ones have to be cleaned up, they don't currently pass
  # - CI_TESTS=fav_gems
  # - CI_TESTS=sinatra
  # - CI_TESTS=examples
notifications:
    email: false
    irc: "irc.freenode.org#maglev-ruby"
